export const COMPRESSED_CALENDAR_POLICY_VERSION = 1 as const;
export const GAME_MINUTES_PER_HOUR = 60 as const;
export const HOURS_PER_SIMULATION_CYCLE = 24 as const;
export const MONTHS_PER_CALENDAR_YEAR = 12 as const;

export const MINUTES_PER_SIMULATION_CYCLE = GAME_MINUTES_PER_HOUR * HOURS_PER_SIMULATION_CYCLE;
