export { HeightLattice, TerrainInvariantError } from './height-lattice.js';
export type { TerrainInvariantErrorCode } from './height-lattice.js';
export { classifyTerrainShape, normalizeTerrainCorners } from './shape-classifier.js';
export type { TerrainShape } from './shape-classifier.js';
export { decodeTerrainSaveV1, encodeTerrainSaveV1 } from './serialization.js';
export type { TerrainSaveError, TerrainSaveErrorCode, TerrainSaveV1 } from './serialization.js';
export { createTerrainMap } from './terrain-map.js';
export type { CreateTerrainMapInput, TerrainMap, TerrainSnapshot } from './terrain-map.js';
export { CELL_TRIANGLES, selectTerrainDiagonal } from './topology.js';
export type { TerrainCorner, TerrainCorners, TerrainDiagonal } from './topology.js';
export { validateTerrainInput } from './validation.js';
export type { TerrainValidationIssue, TerrainValidationIssueCode } from './validation.js';
